#!/bin/sh
ssh proseline.com <<'SCRIPT'
cd proseline.com
old_hash="$(shasum package-lock.json)"
git fetch origin
git reset --hard origin/master
new_hash="$(shasum package-lock.json)"
[ "$old_hash" != "$new_hash" ] && npm ci
systemctl --user restart proseline
SCRIPT
